Added Service.oas_file field to save copy of OAS instead of fetching by URL
maykinmedia/zgw-consumers pull request #25
Opened 2021-11-18 13:55 UTC by Bartvaderkin

2021-11-18 14:04 UTC, Bartvaderkin commented
I thought about renaming the existing `.oas` URLField to `.oas_url` but decided against it for compatibility reasons.

2021-11-19 09:14 UTC, sergei-maertens requested changes

2021-11-19 09:14 UTC, sergei-maertens commented on zgw_consumers/models.py
> +        null=True,
`FileField` under the hood is a string-based field, so you shouldn't make those nullable

```suggestion
```

2021-11-19 10:34 UTC, Bartvaderkin commented
I removed the unnecessary null attribute.

2021-11-19 10:56 UTC, sergei-maertens approved these changes

2021-11-19 10:56 UTC, merged