:sparkles: clear get_zaaktypen cache when type ztc gets saved
maykinmedia/zgw-consumers pull request #65
Opened 2023-05-24 08:01 UTC by bart-maykin

Added function that clears the get_zaaktypen cache if new instance of ztc object gets saved

2023-05-24 10:50 UTC, CharString requested changes
I'd still like to see the test cases that show this change is needed. There's a TODO comment above, that indicates this implementation may change. The testcases will make sure that new code will not break our current uses.

2023-05-25 08:14 UTC, sergei-maertens approved these changes

2023-05-25 08:15 UTC, CharString approved these changes

2023-05-25 08:16 UTC, sergei-maertens commented
> I'd still like to see the test cases that show this change is needed. There's a TODO comment above, that indicates this implementation may change. The testcases will make sure that new code will not break our current uses.

Discussed during standup - lru_cache should've never been added in the first place because there's no invalidation mechanism if the remote API data changes (new version of zaaktype/zaaktype added etc.). A test to express this seems a bit silly to me and doesn't trade-off well with the required change.

2023-05-25 08:16 UTC, merged